# Site Settings
locale: "en-US"
title: "Edison Chen"
title_separator: "-"
subtitle:
name: "Edison Chen"
description: "Edison Chen - Projects and CV"

# GitHub Pages URLs
url: "https://cornell-mae-ug.github.io"
baseurl: "/fa25-portfolio-ec876-design"   # repo name with leading slash

# Theme and Style
theme: jekyll-theme-minimal
color_scheme: light

sass:
  style: compressed

# Outputting
permalink: /:categories/:title/

collections:
  pages:
    output: true
  projects:
    output: true
    permalink: /:collection/:path/

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Plugins
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

